version: "3.8"

services:
  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - php
      - mysql

  # Database Service
  mysql:
    image: mysql:8
    container_name: laravel_database
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=store
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql

  #PHP Service
  php:
    container_name: laravel_application
    build:
        context: .
        dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - 9000:9000
    depends_on:
      - mysql
  # Application Service
  # app:
  #   container_name: blog
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/var/www
  #   ports:
  #     - "9000:9000"
  #   working_dir: /var/www

#top levelVolume 
#create a volume name is db-data
volumes:
    db-data: ~
