version: "3.8"
services:
  #PHP Service
  php:
    build:
        context: .
        target: php
        args:
            - APP_ENV=${APP_ENV}
    environment:
        - APP_ENV=${APP_ENV}
        - CONTAINER_ROLE=app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - 8000:8000
    depends_on:
      - mysql
  # Database Service
  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      # - MYSQL_USER=${DB_USERNAME}
      # MYSQL_PASSWORD: "${DB_PASSWORD}"
      - MYSQL_SERVICE_NAME=mysql
    volumes:
      - db-data:/var/lib/mysql

#top levelVolume 
#create a volume name is db-data
volumes:
    db-data: ~
